version: '3'
services:
  invoice-app:
    build:
      dockerfile: Dockerfile
      context: .
    image: rogerfernandes/invoice-app
    container_name: invoice-app
    ports:
      - '80:80'
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      FLASK_DB_HOST: invoice-app-mysql
      FLASK_DB_ROOT_PASSWORD: 123456
      WAIT_HOSTS: invoice-app-mysql:3306
    depends_on:
      - database
    restart: always

  database:
    image: mysql
    container_name: invoice-app-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
